nginx:
  build: "nginx"
  ports:
    - "5000:5000"
    - "5001:5001"
    - "5002:5002"
    - "5011:5011"
    - "5440:5440"
    - "5441:5441"
    - "5442:5442"
    - "5443:5443"
    - "5444:5444"
    - "5445:5445"
    - "5446:5446"
    - "5447:5447"
    - "5448:5448"
    - "6666:6666"
  links:
    - registryv1:registryv1
    - registryv2:registryv2
    - malevolent:malevolent
registryv1:
  image: registry:0.9.1
  ports:
    - "5000"
registryv2:
  build: "../../"
  ports:
    - "5000"
malevolent:
  build: "malevolent"
  command: "-l 0.0.0.0:5000 -u http://registryv2:5000"
  links:
    - registryv2:registryv2
  ports:
    - "5000"
